import os
import sqlite3
import sys
import shutil
import getpass
from datetime import datetime

# For Windows Chrome cookie decryption
try:
    import win32crypt
except ImportError:
    win32crypt = None
    print("[WARN] win32crypt not available. Encrypted cookies may not be readable.")

def get_chrome_path(custom_path=None):
    if custom_path:
        return custom_path
    return os.path.expandvars(r"%LOCALAPPDATA%\Google\Chrome\User Data\Default\Cookies")

NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# This file was generated by extract_chrome_cookies.py\n"

# Helper to decrypt cookie value (Windows)
def decrypt_cookie_value(encrypted_value):
    if win32crypt:
        try:
            return win32crypt.CryptUnprotectData(encrypted_value, None, None, None, 0)[1].decode()
        except Exception:
            return ""
    return encrypted_value.decode(errors='ignore')

def export_cookies(output_file, fmt='netscape', cookies_path=None):
    chrome_path = get_chrome_path(cookies_path)
    if not os.path.exists(chrome_path):
        print(f"[ERROR] Chrome cookies file not found: {chrome_path}")
        return False
    # Open the database in read-only mode using SQLite URI (works while Chrome is open)
    try:
        conn = sqlite3.connect(f'file:{chrome_path}?mode=ro', uri=True)
    except Exception as e:
        print(f"[ERROR] Could not open Chrome cookies DB: {chrome_path}\n{e}")
        return False
    cursor = conn.cursor()
    cookies = []
    try:
        cursor.execute("SELECT host_key, path, is_secure, expires_utc, name, value, encrypted_value FROM cookies")
        for row in cursor.fetchall():
            host, path, secure, expires, name, value, encrypted_value = row
            if not value and encrypted_value:
                value = decrypt_cookie_value(encrypted_value)
            flag = "TRUE" if host.startswith('.') else "FALSE"
            secure_str = "TRUE" if secure else "FALSE"
            expiry = int(expires / 1000000) if expires else 0
            cookies.append({
                'host': host,
                'flag': flag,
                'path': path,
                'secure': secure_str,
                'expiry': expiry,
                'name': name,
                'value': value
            })
    finally:
        conn.close()
    if fmt == 'netscape':
        lines = [NETSCAPE_HEADER]
        for c in cookies:
            lines.append(f"{c['host']}\t{c['flag']}\t{c['path']}\t{c['secure']}\t{c['expiry']}\t{c['name']}\t{c['value']}\n")
        with open(output_file, 'w', encoding='utf-8') as f:
            f.writelines(lines)
        print(f"[INFO] Exported cookies in Netscape format to {output_file}")
    elif fmt == 'json':
        import json
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(cookies, f, indent=2)
        print(f"[INFO] Exported cookies in JSON format to {output_file}")
    elif fmt == 'txt':
        lines = ["host\tflag\tpath\tsecure\texpiry\tname\tvalue\n"]
        for c in cookies:
            lines.append(f"{c['host']}\t{c['flag']}\t{c['path']}\t{c['secure']}\t{c['expiry']}\t{c['name']}\t{c['value']}\n")
        with open(output_file, 'w', encoding='utf-8') as f:
            f.writelines(lines)
        print(f"[INFO] Exported cookies in plain text to {output_file}")
    else:
        print(f"[ERROR] Unknown format: {fmt}")
        return False
    return True

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Export Chrome cookies to Netscape, JSON, or TXT format.")
    parser.add_argument("output_file", nargs="?", default="webscraper/cookies_netscape_format.txt", help="Output file path")
    parser.add_argument("--format", choices=["netscape", "json", "txt"], default="netscape", help="Output format")
    parser.add_argument("--cookies", type=str, default=None, help="Path to Chrome Cookies database")
    args = parser.parse_args()
    export_cookies(args.output_file, args.format, args.cookies)
